# Generated by Django 3.2.8 on 2021-10-26 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0002_remove_post_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('date_created',)},
        ),
    ]
